// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDegxm3r-CHgiZLI46LB536KK_YTrvwAB0',
    appId: '1:966076762511:web:5bb97ac59b26bbba2523fa',
    messagingSenderId: '966076762511',
    projectId: 'messageapp-4c0bd',
    authDomain: 'messageapp-4c0bd.firebaseapp.com',
    storageBucket: 'messageapp-4c0bd.firebasestorage.app',
    measurementId: 'G-CDVS4H4ZPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOc9KbhAsPJEIldDa_GcXVWiNJS3i9NhY',
    appId: '1:966076762511:android:b4a32d761651bec82523fa',
    messagingSenderId: '966076762511',
    projectId: 'messageapp-4c0bd',
    storageBucket: 'messageapp-4c0bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASlOEg121bTu200ZP7Rpeujte7v4Sd6bw',
    appId: '1:966076762511:ios:e5b76df1686d2f5e2523fa',
    messagingSenderId: '966076762511',
    projectId: 'messageapp-4c0bd',
    storageBucket: 'messageapp-4c0bd.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASlOEg121bTu200ZP7Rpeujte7v4Sd6bw',
    appId: '1:966076762511:ios:e5b76df1686d2f5e2523fa',
    messagingSenderId: '966076762511',
    projectId: 'messageapp-4c0bd',
    storageBucket: 'messageapp-4c0bd.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDegxm3r-CHgiZLI46LB536KK_YTrvwAB0',
    appId: '1:966076762511:web:028f069016bd89b02523fa',
    messagingSenderId: '966076762511',
    projectId: 'messageapp-4c0bd',
    authDomain: 'messageapp-4c0bd.firebaseapp.com',
    storageBucket: 'messageapp-4c0bd.firebasestorage.app',
    measurementId: 'G-HBEHKYEPX0',
  );
}
